[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path=stdout", "--show-stats=false"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-lsp"]

[language.debugger]
name = "go"
transport = "stdio"
command = "dlv"
args = ["dap"]
templates = []
